[package]
name = "api-investo"
version = "0.1.0"
edition = "2024"

[dependencies]
# On hérite tout du workspace racine
axum = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
dotenvy = { workspace = true }
jsonwebtoken = { workspace = true }
tower-http = { workspace = true }
hashed_password = { workspace = true }
tokio = { workspace = true }

# On ajoute le lien vers le module partagé
shared = { path = "../shared" }
