[package]
name = "api-investo"
version = "0.1.0"
edition = "2024"

[dependencies]
tower-http = { version = "0.5", features = ["cors", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
axum = "0.8.9"
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-rustls-ring-webpki", "postgres", "chrono", "uuid" ] }
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15.7"
serde = "1.0.228"
serde_json = "1.0.143"
chrono = { version = "0.4.41", features = ["serde"] }
uuid = { version = "1.17.0", features = ["serde", "v4"] }
hashed_password = "1.3.0"